apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edaf-source-sensor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/vishalvyas1/crossplane-v2.git"
    targetRevision: HEAD
    path: "argo-events/edaf-source-sensor"
    helm:
      parameters:
        - name: namespaceOverride
          value: "argo-events"
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
