apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-source-dummy
  namespace: argo-events
spec:
  service:
    ports:
      - port: 13000
        targetPort: 13000
  webhook:
    example-webhook:
      port: "13000"
      endpoint: "/dummy"
      method: "POST"
